name: seba_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  easy_date_timeline: ^1.0.3
  equatable: ^2.0.5
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  hooks_riverpod: ^2.4.10
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_localizations:
    sdk: flutter
  wakelock: ^0.6.2
  geolocator: ^11.0.0
  image: ^4.1.7
  share_plus: ^6.3.4
  flutter_spinkit: ^5.2.0
  email_validator: ^2.1.17
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  generate: true 

  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Cairo
      fonts: 
        - asset: assets/fonts/CairoMedium.ttf
          weight: 500
        - asset: assets/fonts/CairoExtraLight.ttf
          weight: 200
        - asset: assets/fonts/CairoBold.ttf
          weight: 700
